config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  get 'inquiries/new'
  post 'inquiries/confirm'
  post 'inquiries/thanks'

  devise_for :users
  patch 'users/withdraw' => 'users#withdraw', as: 'withdraw'
  resources :users, only: [:show, :index, :edit, :update] do
    resources :payments, only: [:create, :index]
  end

  get 'comics' => "pictures#comics", as: :comics
  get 'illustrations' => "pictures#illustrations", as: :illustrations
  get 'bookmarks' => "pictures#bookmarks", as: :bookmarks
  resources :pictures do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
    resource :bookmarks, only: [:create, :destroy]
  end
  
  resources :genres, only: [:index, :create,:edit, :update]
  resources :messages, only: [:create]
  resources :rooms, only: [:create, :show, :index]
  get 'search', to: "searches#search"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :payments, dependent: :destroy
  has_many :pictures, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :rooms, through: :entries
  attachment :profile_image

  enum status: { 無料会員: 0, 有料会員: 1, 講師: 2 }

  # 有効会員のみログインできる機能
  def active_for_authentication?
    super && (self.is_deleted == false)
  end

  # ユーザ検索機能
  def self.search_user(word)
    where(is_deleted: false).where("name LIKE?","%#{word}%")
                            .or(where(is_deleted: false)
                            .where("nickname LIKE?","%#{word}%"))
  end

  # @userとログインユーザがEntryモデルに相互登録されていることを確かめるロジック
  def login_user_check_entry(other_user)
    result = {
      isRoom: false,
      roomId: nil,
      room: nil,
      entry: nil
    }

    currentUserEntry = entries
    userEntry = other_user.entries
    isRoom = false
    currentUserEntry.each do |cu|
      userEntry.each do |u|
        if cu.room_id == u.room_id
          isRoom = true
          result[:isRoom] = isRoom
          result[:roomId] = cu.room_id
        end
      end
    end
    unless isRoom
      result[:room] = Room.new
      result[:entry] = Entry.new
    end
    result
  end

  validates :name, :name_kana, :email, :status, presence: true
  validates :nickname, length: {maximum: 25}
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :edit_possible_user, only: [:edit,:update]
  before_action :index_access_user, only: [:index]

  def index
    @users = User.where(status: ["無料会員", "有料会員"]).page(params[:page]).per(10)
  end

  def show
    @user = User.find(params[:id])
    if @user.is_deleted && ["有料会員", "無料会員"].include?(current_user.status)
      redirect_to user_path(current_user)
    end
    # @userとログインユーザがEntryモデルに相互登録されていることを確かめるロジック
    if user_signed_in? && @user != current_user
      login_user_check_entry = current_user.login_user_check_entry(@user)
      if login_user_check_entry[:isRoom]
        @isRoom = login_user_check_entry[:isRoom]
        @roomId = login_user_check_entry[:roomId]
      else
        @room = login_user_check_entry[:room]
        @entry = login_user_check_entry[:entry]
      end
    end
    # @userとログインユーザがEntryモデルに相互登録されていることを確かめるロジック
    @comic_pictures = @user.pictures.user_picture_limit4("マンガ")
    @illustration_pictures = @user.pictures.user_picture_limit4("イラスト")
    @pictures = Picture.genre_user_active.limit(4)
    @admin_user = @user != current_user && 
                  ['講師'].include?(current_user.status) && 
                  ['有料会員','無料会員'].include?(@user.status) 
    @admin_chat_link = !@user.is_deleted && 
                       @user != current_user && 
                       ["有料会員", "講師"].include?(@user.status) && 
                       ["講師"].include?(current_user.status)
    @user_picture_empty = @user.pictures.empty? ||
                          @illustration_pictures.empty? && 
                          @comic_pictures.empty?
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), alert: "更新が無事に完了しました。"
    else
      render :edit
    end
  end

  def withdraw
    @user = User.find(current_user.id)
    if @user.update(is_deleted: true)   
      reset_session
      redirect_to root_path, alert: "退会処理が完了しました。今までのご利用ありがとうございました。"
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user)
          .permit(:name, :name_kana, :profile_image, :nickname, :postal_code, :address, :telephone_number, :email, :status, :is_deleted)
  end

  def edit_possible_user
    @user = User.find(params[:id])
    unless @user == current_user || current_user.status == "講師" && ['有料会員','無料会員'].include?(@user.status)
      redirect_to user_path(current_user)
    end
  end

  def index_access_user
    unless current_user.status == "講師"
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container">
	<div class="row">
		<!-- 題名 -->
		<% if @user == current_user %>
			<h2 class="edit-user-title">登録情報編集</h2>
		<% elsif current_user.status == "講師" %>
			<h2 class="edit-user-title"><%= @user.name %>さんの登録情報編集</h2>
		<% end %>
		<!-- 題名 -->

		<%= render "layouts/errors", validation: @user %>

		<%= form_for @user do |f| %>
			<!-- ログインしているユーザ用フォーム -->
			<% if @user == current_user %>
				<div class="col-sm-5 col-md-4 col-md-offset-1 form-space">
					<%= f.attachment_field :profile_image %>
					<div class="col-md-10 form-space">
		        <label>ニックネーム</label><br>
		        <%= f.text_field :nickname, autofocus: true, autocomplete: "name_kana", class: "form-control" %>
		      </div>
				</div>
			<!-- ログインしているユーザ用フォーム -->

			<!-- 管理者用フォーム -->
			<% elsif current_user.status == "講師" %>
				<div class="col-sm-5 col-md-4 col-md-offset-1 form-space">
					<div class="col-sm-12 col-md-12">
						<label>会員ステータス</label><br>
						<label><%= f.radio_button :status, :無料会員 %> 無料会員</label>
	    			<label><%= f.radio_button :status, :有料会員, style: "margin-left: 20px;" %> 有料会員</label>
	    		</div>
	    		<div class="col-sm-12 col-md-12 form-space">
						<label>有効/退会</label><br>
						<label><%= f.radio_button :is_deleted, "false" %> 有効</label>
	    			<label><%= f.radio_button :is_deleted, "true", style: "margin-left: 20px;" %> 退会</label>
	    		</div>

	    		<div class="col-sm-12 col-md-12 form-space">
						<label class="attention">講師として登録しますか？</label><br>
						<label><%= f.radio_button :status, :講師 %> はい</label>
	    		</div>
				</div>
			<!-- 管理者用フォーム -->
			<% end %>

			<div class="col-sm-5 col-md-6">
				<div class="col-md-7 form-space">
	        <label>氏名(半角スペースなし)</label><br>
	        <%= f.text_field :name, autofocus: true, autocomplete: "name", class: "form-control", :required => true %><br>
         </div>

        <div class="col-md-7">
	        <label>氏名(かな、半角スペースなし)</label><br>
	        <%= f.text_field :name_kana, autofocus: true, autocomplete: "name_kana", class: "form-control", :required => true %><br>
	      </div>

	      <!-- 有料会員登録必須 -->
	      <% if @user.status == "有料会員" %>
					<div class="col-md-7">
			      <label>郵便番号</label><br>
			      <%= f.text_field :postal_code, autofocus: true, autocomplete: "postal_code", class: "form-control", :required => true %><br>
			   	</div>

			    <div  class="col-md-12">
	         	<label>住所</label><br>
	          <%= f.text_field :address, autofocus: true, autocomplete: "address", class: "form-control", :required => true %><br>
	        </div>

	        <div  class="col-md-7">
	          <label>電話番号</label><br>
	          <%= f.text_field :telephone_number, autofocus: true, autocomplete: "telephone_number", class: "form-control", :required => true %><br>
	        </div>
	        <!-- 有料会員登録必須 -->
	      <% else %>
	       	<div class="col-md-7">
			      <label>郵便番号</label><br>
			      <%= f.text_field :postal_code, autofocus: true, autocomplete: "postal_code", class: "form-control" %><br>
			   	</div>

			    <div  class="col-md-12">
	         	<label>住所</label><br>
	          <%= f.text_field :address, autofocus: true, autocomplete: "address", class: "form-control" %><br>
	        </div>

	        <div  class="col-md-7">
	          <label>電話番号</label><br>
	          <%= f.text_field :telephone_number, autofocus: true, autocomplete: "telephone_number", class: "form-control" %><br>
	        </div>
	      <% end %>

        <div  class="col-md-7">
         	<label>メールアドレス</label><br>
          <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "form-control", :required => true %><br>
        </div>

        <div  class="col-md-7">
        	<%= f.submit "登録する", data: { confirm: '入力内容にお間違いないですか？' }, class: "btn btn-primary btn-block" %>
        </div>
        <!-- 退会リンク -->
        <% if @user == current_user %>
	        <div  class="col-xs-5 col-sm-5 withdraw">
	        	<%= link_to "退会する" , withdraw_path, method: :patch, "data-confirm" => "今までのサービスが利用できなくなります。本当に退会しますか？", class: "btn btn-danger btn-block" %>
	        </div>
	      <% end %>
	      <!-- 退会リンク -->
      </div>
		<% end %>
	</div>
</div>

app/views/users/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-sm-offset-2 signin-title">
			<h2>会員一覧</h2>
		</div>
		<div class="col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">
			<table class="table">
				<thead>
					<tr class="active">
						<th>会員ステータス</th>
						<th>氏名</th>
						<th>有効/退会</th>
						<th>支払い</th>
					</tr>
				</thead>
				<tbody>
					<% @users.each do |user| %>
						<tr>
							<td class="nowrap"><%= user.status %></td>
							<td class="word-break"><%= link_to user.name, user_path(user) %></td>
							<td class="nowrap">
  								<% unless user.is_deleted %>
  									<p>有効</p>
  								<% else %>
  									<p>退会済み</p>	
  								<% end %>
							</td>
							<td class="nowrap"><%= link_to "支払い情報へ", user_payments_path(user) %></td>
						</tr>
					<% end %>	
				</tbody>
			</table>
			<div class="col-xs-12 center">
				<%= paginate @users %>
			</div>
		</div>
	</div>
</div>



	

app/views/users/show.html.erb
<!-- 更新成功alert -->
<% if flash[:alert] %>
  <div class="alert alert-success">
    <%= flash[:alert] %>
  </div>
<% end %>
<!-- 更新成功alert -->

<div class="container">
	<div class="row">
		<!-- ユーザプロフィール -->
		<div class="col-sm-5 col-md-2 profile-image">
			<%= attachment_image_tag @user, :profile_image, size: "200x200", format: "jpeg", class: "img-circle pull-left profile-img", fallback: "no_image_square.jpg" %>
		</div>
		<div class="col-md-9 col-md-offset-1">
			<div class="col-md-12">
				<%if @user.nickname.blank? %>
					<h2 class="profile word-break"><%= @user.name %></h2>
				<% else %>
					<h2 class="profile word-break"><%= @user.nickname %></h2>
				<% end %>
			</div>
		</div>

		<div class="col-md-2 col-md-offset-1">	
			<div class="col-md-12">
				<h4><%= @user.status %></h4>
			</div>
		</div>
		<!-- ユーザプロフィール -->

		<!-- マイページ用リンク -->
		<% if @user == current_user %>
			<div class="col-md-5">
				<div class="col-md-12 user-link">			
					<%= link_to "登録情報を編集する", edit_user_path(current_user) %>
				</div>

				<div class="col-md-12 bookmark-link">			
					<%= link_to "お気に入り", bookmarks_path %>
				</div>

				<% if ["講師","有料会員"].include?(@user.status) %>
					<%= link_to "作品を投稿する", new_picture_path, class: "btn btn-primary", style: "margin-right: 10px;" %>
					<%= link_to "チャットする", rooms_path, class: "btn btn-warning" %>	
				<% end %>
			</div>
		<% end %>
		<!-- マイページ用リンク -->

		<div class="col-md-7">
			<!-- 講師専用会員情報閲覧・編集 -->
			<% if @admin_user%>
				<table class="table table-bordered">
					<tbody>
						<tr>
							<th class="warning nowrap">氏名</th>
							<td class="word-break"><%= @user.name %></td>
						</tr>
						<tr>
							<th class="warning nowrap">氏名(かな)</th>
							<td class="word-break"><%= @user.name_kana %></td>
						</tr>
						<tr>
							<th class="warning nowrap">郵便番号</th>
							<td class="word-break"><%= @user.postal_code %></td>
						</tr>
						<tr>
							<th class="warning nowrap">住所</th>
							<td class="word-break"><%= @user.address %></td>
						</tr>
						<tr>
							<th class="warning nowrap">電話番号</th>
							<td class="word-break"><%= @user.telephone_number %></td>
						</tr>
						<tr>
							<th class="warning nowrap">メールアドレス</th>
							<td class="word-break"><%= @user.email %></td>
						</tr>
					</tbody>
				</table>
				<div class="user-link">
					<%= link_to "登録情報を編集する", edit_user_path(@user) %>
				</div>
			<% end %>
			<!-- 講師専用会員情報閲覧・編集 -->

			<!-- 講師専用チャット開始ボタン -->
			<% if @admin_chat_link %>
				<% if @isRoom %>
			  	<%= link_to "チャットする", room_path(@roomId), class: "btn btn-primary" %>
			  <% else %>
			   	<%= form_for @room do |f| %>
			      <%= fields_for @entry do |e| %>
			        <%= e.hidden_field :user_id, value: @user.id %>
			     	<% end %>
			      <%= f.submit "この人とチャットを始める", class:"btn btn-primary"%>
			    <% end %>
			  <% end %>
			<% end %>
			<!-- 講師専用チャット開始ボタン -->
		</div>
	</div>
</div>

<div class="container">
	<!-- @userの投稿イラスト一覧 -->
	<% if  @illustration_pictures.exists? %>
		<h2 class="picture-title">イラスト作品</h2>
		<%= render "pictures/users_picture", pictures:  @illustration_pictures %>
	<% end %>

	<% if  @illustration_pictures.count > 3 %>
		<div class="pull-right">
			<%= link_to "もっと見る", controller: "pictures", action: "illustrations", user_id: @user.id %>
		</div>
	<% end %>
	<!-- @userの投稿イラスト一覧 -->

	<!-- @userの投稿マンガ一覧 -->
	<% if @comic_pictures.exists? %>
		<h2 class="picture-title">マンガ作品</h2>
		<%= render "pictures/users_picture", pictures:  @comic_pictures %>
	<% end %>

	<% if @comic_pictures.count > 3 %>
		<div class="pull-right">
			<%= link_to "もっと見る", controller: "pictures", action: "comics", user_id: @user.id %>
		</div>
	<% end %>
	<!-- @userの投稿マンガ一覧 -->

	<!-- 未投稿時及び無料会員用オススメ一覧(ログインユーザのみ) -->
	<%if @user == current_user %>
		<% if @user_picture_empty %>
			<h2 class="picture-title">おすすめ作品</h2>
			<div class="picture-image">
				<%= render "pictures/recommendation_picture", pictures:  @pictures %>
			</div>

	　　<% if @pictures.count > 3 %>
				<div class="pull-right">
					<%= link_to "もっと見る", pictures_path %>
				</div>
			<% end %>
		<% end %>
	<% end %>
	<!-- 未投稿時及び無料会員用オススメ一覧(ログインユーザのみ) -->
</div>