config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  get 'inquiries/new'
  post 'inquiries/confirm'
  post 'inquiries/thanks'

  devise_for :users
  patch 'users/withdraw' => 'users#withdraw', as: 'withdraw'
  resources :users, only: [:show, :index, :edit, :update] do
    resources :payments, only: [:create, :index]
  end

  get 'comics' => "pictures#comics", as: :comics
  get 'illustrations' => "pictures#illustrations", as: :illustrations
  get 'bookmarks' => "pictures#bookmarks", as: :bookmarks
  resources :pictures do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
    resource :bookmarks, only: [:create, :destroy]
  end
  
  resources :genres, only: [:index, :create,:edit, :update]
  resources :messages, only: [:create]
  resources :rooms, only: [:create, :show, :index]
  get 'search', to: "searches#search"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :user
  belongs_to :genre
  has_many :picture_images, dependent: :destroy
  accepts_nested_attributes_for :picture_images
  accepts_attachments_for :picture_images, attachment: :image
  has_many :bookmarks, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy

  enum status: { イラスト: 0, マンガ: 1 }

  scope :genre_active,  -> { joins(:genre).where(genres: {is_active: true}) }
  scope :user_active,  -> { joins(:user).where(users: {is_deleted: false}) }

  # ログインユーザがすでにいいねしているか確かめるロジック
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  # ログインユーザがすでにお気に入り登録しているか確かめるロジック
  def bookmark_by?(user)
    bookmarks.where(user_id: user.id).exists?
  end
   
  # ユーザ詳細画面にて投稿された作品を表示するロジック
  def self.user_picture_limit4(status)
    where(status: status).joins(:genre)
                         .where(genres: {is_active: true})
                         .order(id: "DESC")
                         .limit(4)
  end

  # ユーザ詳細画面にて作品を表示するロジック
  def self.genre_user_active
    joins(:genre, :user).where(genres: {is_active: true}, users: {is_deleted: false})                    
  end

  # 検索窓でイラストまたはマンガを探すロジック
  def self.search_picture(status, word)
    where(status: status).where("title LIKE?","%#{word}%")
                         .joins(:genre, :user)
                         .where(genres: {is_active: true}, users: {is_deleted: false})
  end

  # 検索窓でジャンル関連の作品を探すロジック
  def self.search_genre_picture(genres)
    where(genre_id: genres).joins(:user).where(users: {is_deleted: false})
  end

  # ジャンルとユーザが有効で、マンガまたはイラストを取得するロジック
  def self.picture_user_genre_active(status)
    where(status: status).joins(:genre, :user)
                         .where(genres: {is_active: true} ,users: {is_deleted: false})
  end

  # ジャンルが有効で、マンガまたはイラストを取得するロジック
  def self.picture_genre_active(status)
    where(status: status).joins(:genre)
                         .where(genres: {is_active: true})
  end

  # ユーザが有効で、マンガまたはイラストを取得するロジック
  def self.picture_user_active(status)
    where(status: status).joins(:user)
                         .where(users: {is_deleted: false})
  end

  validates :title, :introduction, :status, presence: true
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :authenticate_user!
  before_action :picture_add_user, only: [:new,:create]
  before_action :picture_destroy_user, only: [:destroy]
  before_action :picture_edit_user, only: [:edit, :update]

  def new
    @picture = Picture.new
    @picture.picture_images.build
  end

  def create
    @picture = Picture.new picture_params
    @picture.user_id = current_user.id
    if @picture.save
      redirect_to picture_path(@picture), alert: "作品を無事に登録できました。"
    else 
      render :new
    end
  end

  def show
    @picture = Picture.find(params[:id])
    if @picture.user.is_deleted && ['有料会員', '無料会員'].include?(current_user.status)
      redirect_to user_path(current_user)
    end
    if !@picture.genre.is_active && ['有料会員', '無料会員'].include?(current_user.status)
      redirect_to user_path(current_user)
    end
    @picture_destroy_user = @picture.user == current_user ||
                            current_user.status == "講師"
    @pictures = @picture.user.pictures.limit(3)
    @picture_images = @picture.picture_images
    @comment = Comment.new
  end

  def index
    @genres = Genre.where(is_active: true)
    if params[:user_id]
      @user = User.find(params[:user_id])
      if @user.is_deleted && ['有料会員', '無料会員'].include?(current_user.status)
        redirect_to user_path(current_user)
      end
      @pictures = @user.pictures.genre_active.page(params[:page]).per(30)
    elsif params[:genre_id]
      @genre = Genre.find(params[:genre_id])
      @pictures = @genre.pictures.user_active.page(params[:page]).per(18)
    else
      @pictures = Picture.genre_user_active.page(params[:page]).per(12)
    end
  end

  def bookmarks
    @bookmarks = current_user.bookmarks.joins(:user).where(users: {is_deleted: false})
  end

  def comics
    @genres = Genre.where(is_active: true)
    if params[:user_id]
      @user = User.find(params[:user_id])
      if @user.is_deleted && ['有料会員', '無料会員'].include?(current_user.status)
        redirect_to user_path(current_user)
      end
      @pictures = @user.pictures.picture_genre_active("マンガ").page(params[:page]).per(30)
    elsif params[:genre_id]
      @genre = Genre.find(params[:genre_id])
      @pictures = @genre.pictures.picture_user_active("マンガ").page(params[:page]).per(18)
    else
      @pictures = Picture.picture_user_genre_active("マンガ").page(params[:page]).per(12)
    end
  end

  def illustrations
    @genres = Genre.where(is_active: true)
    if params[:user_id]
      @user = User.find(params[:user_id])
      if @user.is_deleted && ['有料会員', '無料会員'].include?(current_user.status)
        redirect_to user_path(current_user)
      end
      @pictures = @user.pictures.picture_genre_active("イラスト").page(params[:page]).per(30)
    elsif params[:genre_id]
      @genre = Genre.find(params[:genre_id])
      @pictures = @genre.pictures.picture_user_active("イラスト").page(params[:page]).per(18)
    else
      @pictures = Picture.picture_user_genre_active("イラスト").page(params[:page]).per(12)
    end
  end

  def edit
    @picture = Picture.find(params[:id])
  end

  def update
    @picture = Picture.find(params[:id])
    if @picture.update(picture_params)
      redirect_to picture_path(@picture), alert: "作品を無事に更新できました。"
    else
      render :edit
    end
  end

  def destroy
    @picture = Picture.find(params[:id])
    @picture.destroy
    redirect_to user_path(current_user), alert: "削除が無事に完了しました。"
  end

  private
  def picture_params
    params.require(:picture)
          .permit(:title, :introduction, :genre_id, :status, picture_images_images: [])
  end

  def picture_add_user
    if current_user.status == "無料会員"
      redirect_to user_path(current_user)
    end
  end

  def picture_destroy_user
    @picture = Picture.find(params[:id])
    unless @picture.user == current_user || current_user.status == "講師"
      redirect_to user_path(current_user)
    end
  end

  def picture_edit_user
    @picture = Picture.find(params[:id])
    unless @picture.user == current_user
      redirect_to user_path(current_user)
    end
  end

  def check_registration(user, login_user)
    user.is_deleted && login_user.status == "講師"
  end
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/pictures/_evaluation.html.erb
<% if picture.user == current_user || current_user.status == "講師" %>
	<h4 class="evaluation">コメントから判断したみんなの評価</h4>
	<% if picture.comments.exists? %>
		<h1><%= (picture.comments.sum(:score) / picture.comments.count).round(1) %></h1>
	<% else %>
		<h1>0.0</h1>
	<% end %>
	<div class="col-sm-12 col-md-12 evaluation">
		<p>評価の目安</p>
	</div>
	<div class="col-sm-4 col-md-4">
		<p>-1.0 ~ -0.25: <span class="label label-danger">bad</span></p>
	</div>
	<div class="col-sm-4 col-md-4">
		<p>-0.25 ~ 0.25: <span class="label label-warning">good</span></p>
	</div>
	<div class="col-md-4">
		<p> 0.25 ~ 1.0: <span class="label label-success">very good</span></p>
	</div>	
<% end %>

app/views/pictures/_favorite_bookmark.html.erb
<div class="favorite-bookmark">
	<!-- お気に入り登録 -->
	<% unless picture.user == current_user %> 
		<% if picture.bookmark_by?(current_user) %>
			<div class="bookmark">
				<%= link_to "お気に入りを外す", picture_bookmarks_path(picture), method: :delete, remote: true, class: "btn btn-warning" %>
				</div>
		<% else %>
			<div class="bookmark">
				<%= link_to "お気に入り登録", picture_bookmarks_path(picture), method: :post, remote: true, class: "btn btn-success" %>
			</div>
		<% end %>
	<% end %>
	<!-- お気に入り登録 -->

	<!-- いいね機能 -->
	<% if picture.favorited_by?(current_user) %>
		<%= link_to picture_favorites_path(picture), method: :delete, style: "color: red; margin: 30px 20px 0 0;", remote: true do %>
			<i class="glyphicon glyphicon-heart" ></i>
			<%= picture.favorites.count %>いいね
		<% end %>
	<% else %>
		<%= link_to picture_favorites_path(picture), method: :post, style: "color: black; margin: 30px 20px 0 0;", remote: true do %>
			<i class="glyphicon glyphicon-heart-empty"></i>
			<%= picture.favorites.count %>いいね
		<% end %>
	<% end %>
	<!-- いいね機能 -->
</div>

app/views/pictures/_picture.html.erb
<div class="picture-image">
	<% pictures.each do |picture| %>
		<div class="picture-space">
			<%= link_to picture_path(picture), style: "line-height: 40px;" do %>
				<%= attachment_image_tag picture.picture_images[0], :image, size: "170x170", format: 'jpeg', fallback: "no_image_square.jpg", style: "border-radius: 10px;" %><br>
				<%= picture.title %>
			<% end %>
		</div>
	<% end %>
</div>

app/views/pictures/_picture_form.html.erb
<%= form_with model:[picture], local: true do |f| %>
	<div class="col-sm-4 col-md-7 preview_image">
		<%= f.attachment_field :picture_images_images, multiple: true, class: "form-space" %>
		<!-- 画像プレビュー機能 -->
		<div id="preview">
			<% @picture.picture_images.each do |picture_image| %>
				<%= attachment_image_tag picture_image, :image, format: 'jpeg', fallback: "no_image_square.jpg", size: "150x150"  ,class:"uploaded_image" %>
			<% end %>
		</div>
		<!-- 画像プレビュー機能 -->
	</div>

	<div class="col-sm-5 col-sm-offset-1 col-md-3">
		<div class="form-space">
			<label><%= f.radio_button :status, :マンガ %> マンガ</label>
			<label>
				<%= f.radio_button :status, :イラスト, style: "margin-left: 50px;" %> イラスト
			</label>
		</div>

		<div class="title-space">
			<label class="title-space">タイトル</label><br>
			<%= f.text_field :title, class: "form-control" %><br>
			<label>説明</label><br>
			<%= f.text_area :introduction, class: "form-control", size: "5x5" %><br>
			<label class="space">ジャンル</label>
			<%= f.collection_select :genre_id, Genre.where(is_active: true), :id, :genre, {}, {style: "max-width: 250px;"} %><br>
	  </div>

		<%= f.submit "投稿する", class: "btn btn-primary btn-block", style: "margin-top: 20px;" %>
	</div>
<% end %>


app/views/pictures/_picture_index.erb
<% pictures.each do |picture| %>
	<div class="index-space">
		<%= link_to picture_path(picture), style:"margin-bottom: 50px;" do %>
			<%= attachment_image_tag picture.picture_images[0], :image, size: "170x170", format: "jpeg", fallback: "no_image_square.jpg", style: "border-radius: 10px;" %>
			<div class="index-nowrap">
				<span class="index-title"><%= picture.title %></span>
			</div>
		<% end %>
			
		<%= link_to user_path(picture.user)do %>
			<div class="index-image">
				<%= attachment_image_tag picture.user, :profile_image, size: "50x50", format: "jpeg", fallback: "no_image_square.jpg", class: "img-circle" %>
			</div>
			<div class="index-nowrap">
				<% if picture.user.nickname.blank? %>
					<span class="index-title"><%= picture.user.name %></span>
				<% else %>
					<span class="index-title"><%= picture.user.nickname %></span>
				<% end %>
			</div>
		<% end %>		
	</div>
<% end %>

app/views/pictures/_recommendation_picture.html.erb
<% pictures.each do |picture| %>
	<% if !picture.user.is_deleted %>
		<div class="picture-space">
			<%= link_to picture_path(picture), style:"margin-bottom: 50px;" do %>
				<%= attachment_image_tag picture.picture_images[0], :image, size: "170x170", format: "jpeg", fallback: "no_image_square.jpg", style: "border-radius: 10px;" %>
				<div class="index-nowrap">
					<span class="index-title"><%= picture.title %></span>
				</div>
			<% end %>
			
			<%= link_to user_path(picture.user)do %>
				<div class="index-image">
					<%= attachment_image_tag picture.user, :profile_image, size: "50x50", format: "jpeg", fallback: "no_image_square.jpg", class: "img-circle" %>
				</div>
				<div class="index-nowrap">
					<% if picture.user.nickname.blank? %>
						<span class="index-title"><%= picture.user.name %></span>
					<% else %>
						<span class="index-title"><%= picture.user.nickname %></span>
					<% end %>
				</div>
			<% end %>		
		</div>
	<% end %>
<% end %>

app/views/pictures/_users_picture.html.erb
<div class="picture-image">
	<% pictures.each do |picture| %>
		<div class="picture-space">
			<%= link_to picture_path(picture), style: "line-height: 40px;" do %>
				<%= attachment_image_tag picture.picture_images[0], :image, size: "180x180", format: "jpeg", fallback: "no_image_square.jpg", style: "border-radius: 10px;" %><br>
				<div class="user-picture-nowrap">
					<span class="index-title"><%= picture.title %></span>
				</div>
			<% end %>
		</div>
	<% end %>
</div>

app/views/pictures/bookmarks.html.erb
<div class="container">
	<div class="row">
		<h1 class="signin-title index-pagetitle">お気に入り</h1>
		<!-- お気に入りが存在したら表示 -->
		<% if @bookmarks.exists? %>
			<div class="picture-image">
				<% @bookmarks.each do |bookmark| %>
					<% if bookmark.picture.genre.is_active %>
						<div class="index-space">
							<%= link_to picture_path(bookmark.picture)do %>
								<%= attachment_image_tag bookmark.picture.picture_images[0], :image, size: "170x170", format: "jpeg", fallback: "no_image_square.jpg", style: "border-radius: 10px;" %>
								<div class="index-nowrap">
									<span class="index-title"><%= bookmark.picture.title %></span>
								</div>
							<% end %>
							<%= link_to user_path(bookmark.picture.user)do %>
								<%= attachment_image_tag bookmark.picture.user, :profile_image, size: "50x50", format: "jpeg", fallback: "no_image_square.jpg", class: "img-circle" %>
								<div class="index-nowrap">
									<% if bookmark.picture.user.nickname.blank? %>
										<span class="index-title"><%= bookmark.picture.user.name %></span>
									<% else %>
										<span class="index-title"><%= bookmark.picture.user.nickname %></span>
									<% end %>
								</div>
							<% end %>
						</div>
					<% end %>
				<% end %>
			</div>
			<!-- お気に入りが存在したら表示 -->
		<% else %>
			<div class="nothing">
				<p>お気に入りはありません</p>
			</div>
		<% end %>
	</div>
</div>

app/views/pictures/comics.html.erb
<div class="container">
	<div class="row">
		<h1 class="signin-title index-pagetitle">マンガ</h1>
		<!-- ユーザ詳細画面で「もっと見る」を押したときの処理 -->
		<% if params[:user_id] %>
			<div class="col-md-12 picture-image">
				<%= render "picture_index", pictures: @pictures %>
			</div>
			<div class="col-xs-12 center">
				<%= paginate @pictures %>
			</div>
		 	<!-- ユーザ詳細画面で「もっと見る」を押したときの処理 -->

		<% else %>
			<!-- ジャンル検索、コミックリンクを押したときの処理 -->
			<div class="col-md-3">
				<table class="genre-search">
					<thead>
						<tr>
							<th class="text-center">ジャンル検索</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td><%= link_to ' イラスト', illustrations_path %></td>
						</tr>
						<% @genres.each do |genre| %>
							<tr>
								<td class="word-break">
									<%= link_to genre.genre, controller: "pictures", action: "comics", genre_id: genre.id %>
								</td>
							</tr>
						<% end %>
					</tbody>
				</table>
			</div>
			<div class="col-md-8 col-md-offset-1 picture-image">
				<%= render "recommendation_picture", pictures: @pictures %>
				<div class="col-xs-12 center">
					<%= paginate @pictures %>
				</div>
			</div>
			<!-- ジャンル検索、コミックリンクを押したときの処理 -->		 	
		<% end %>
	</div>
</div>

app/views/pictures/edit.html.erb
<div class="container">
	<div class="row">
		<h1 class="signin-title">作品編集</h1>

		<%= render "layouts/errors", validation: @picture %>
		
		<%= render "picture_form", picture: @picture %>
	</div>
</div>

app/views/pictures/illustrations.html.erb
<div class="container">
	<div class="row">
		<h1 class="signin-title index-pagetitle">イラスト</h1>
		<!-- ユーザ詳細画面で「もっと見る」を押したときの処理 -->
		<% if params[:user_id] %>
			<div class="col-md-12 picture-image">
				<%= render "picture_index", pictures: @pictures %>
			</div>
			<div class="col-xs-12 center">
				<%= paginate @pictures %>
			</div>
		 	<!-- ユーザ詳細画面で「もっと見る」を押したときの処理 -->

		<% else %>
			<!-- ジャンル検索、イラストリンクを押したときの処理 -->
			<div class="col-md-3">
				<table class="genre-search">
					<thead>
						<tr>
							<th class="text-center">ジャンル検索</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td><%= link_to ' マンガ', comics_path %></td>
						</tr>
						<% @genres.each do |genre| %>
							<tr>
								<td class="word-break">
									<%= link_to genre.genre, controller: "pictures", action: "illustrations", genre_id: genre.id %>
								</td>
							</tr>
						<% end %>
					</tbody>
				</table>
			</div>
			<div class="col-md-8 col-md-offset-1 picture-image">
				<%= render "recommendation_picture", pictures: @pictures %>
				<div class="col-xs-12 center">
					<%= paginate @pictures %>
				</div>
			</div>
			<!-- ジャンル検索、イラストリンクを押したときの処理 -->
		<% end %>
	</div>
</div>

app/views/pictures/index.html.erb
<div class="container">
	<div class="row">
		<!-- 作品詳細で「もっと見る」を押したときの処理 -->
		<% if params[:user_id] %>
			<% if @user.nickname.blank? %>
				<h1 class="signin-title index-pagetitle"><%= @user.name %>さんのマンガ・イラスト</h1>
			<% else %>
				<h1 class="signin-title index-pagetitle"><%= @user.nickname %>さんのマンガ・イラスト</h1>
			<% end %>

			<div class="col-md-12 picture-image">
				<%= render "picture_index", pictures: @pictures %>
			</div>
			<div class="col-xs-12 center">
				<%= paginate @pictures %>
			</div>
				
			<!-- 作品詳細で「もっと見る」を押したときの処理 -->

		<% else %>
			<!-- オススメ作品、作品一覧を押したときの処理 -->
			<% if current_user.status == "講師" %>
				<h1 class="signin-title index-pagetitle">作品一覧</h1>
			<% else %> 
				<h1 class="signin-title index-pagetitle">おすすめ作品</h1>
			<% end %>

			<div class="col-md-3">
				<table class="genre-search">
					<thead>
						<tr>
							<th class="text-center">ジャンル検索</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td><%= link_to ' マンガ', comics_path %></td>
						</tr>
						<tr>
							<td><%= link_to ' イラスト', illustrations_path %></td>
						</tr>
						<% @genres.each do |genre| %>
							<tr>
								<td class="word-break">
									<%= link_to genre.genre, controller: "pictures", action: "index", genre_id: genre.id %>
								</td>
							</tr>
						<% end %>
					</tbody>
				</table>
			</div>
			<div class="col-md-8 col-md-offset-1 picture-image">
				<%= render "recommendation_picture", pictures: @pictures %>
				<div class="col-xs-12 center">
					<%= paginate @pictures %>
				</div>
			</div>
			<!-- オススメ作品、作品一覧を押したときの処理 -->
		<% end -%>
	</div>
</div>

app/views/pictures/new.html.erb
<div class="container">
	<div class="row">
		<h1 class="signin-title">新規投稿</h1>

		<%= render "layouts/errors", validation: @picture %>

		<%= render "picture_form", picture: @picture %>
	</div>
</div>

app/views/pictures/show.html.erb
<!-- コメント削除成功alert -->
<div id="comment-delete">
	<%= render 'layouts/success_message' %>
</div>
<!-- コメント削除成功alert -->
<div class="container">
	<div class="row">		
		<div class="col-md-6 col-md-offset-1 pictures">
			<!-- イラスト・マンガ編集削除 -->
			<div class="edit-destroy">
				<% if @picture_destroy_user %>
					<div class="edit">
						<%= link_to "この作品を削除", picture_path(@picture), method: :delete, "data-confirm" => "本当に削除しますか？", class: "btn btn-danger" %>
					</div>
				<% end %> 
				<% if @picture.user == current_user %>
					<div class="destroy">
						<%= link_to "編集・画像再選択", edit_picture_path(@picture), class: "btn btn-success" %>
					</div>
				<% end %>
			</div>
			<!-- イラスト・マンガ編集削除 -->

			<!-- イラスト・マンガスライダー表示 -->
			<div id="slider" dir="rtl">
				<% @picture_images.each do |picture_image| %>
					<%= attachment_image_tag picture_image, :image, format: 'jpeg', fallback: "no_image_square.jpg" %>
				<% end %>
			</div>
			<!-- イラスト・マンガスライダー表示 -->

			<!-- イラスト・マンガ詳細表示 -->
			<div class="col-md-12 picture-details">
				<div class="favorite-bookmark">
					<div class="picture_<%= @picture.id %>">
						<%= render 'favorite_bookmark', picture: @picture %>
					</div>
				</div>

				<h2 class="image-title word-break"><%= @picture.title %></h2>

				<h6>
					<%= link_to user_path(@picture.user) do %>
						<%= attachment_image_tag @picture.user, :profile_image, size: "50x50", format: 'jpeg', fallback: "no_image_square.jpg", class: "img-circle" %>
						<% if @picture.user.nickname.blank? %>
							<%= @picture.user.name %>
						<% else %>
							<%= @picture.user.nickname %>
						<% end %>
					<% end %>
				</h6>

				<p><%= simple_format @picture.introduction, class: "word-break" %></p>
				<div class="comment_evaluation">
					<%= render 'evaluation', picture: @picture %>
				</div>
			</div>
			<!-- イラスト・マンガ詳細表示 -->

			<!-- コメント送信・一覧表示 -->
			<div class="col-md-12 comment">
				<h3>コメント</h3>
				<div id="comments-error">
    			<%= render 'layouts/errors', validation: @comment %>
  			</div>
					<%= form_with model:[@picture, @comment], data: {remote: true} do |f| %>
		        <%= f.text_area :comment, rows: "4", class: "form-control" %>
		        <%= f.submit '送信' %>
		     	<% end %>
	    </div>

			<div class="comment_<%= @picture.id %>">
				<%= render 'comments/index', picture: @picture  %>
			</div>
		</div>
		<!-- コメント送信・一覧表示 -->

		<div class="col-md-3 col-md-offset-1 picture-user">
			<!-- 投稿ユーザプロフィール -->
			<div class="profile-image">
				<%= link_to user_path(@picture.user) do %>
					<%= attachment_image_tag @picture.user, :profile_image, size: "150x150", format: 'jpeg', fallback: "no_image_square.jpg" %>
				<% end %>
			</div>

			<table class="table">
				<tbody>
					<% if @picture.user.nickname.blank? %>
						<tr>
							<th class="nowrap">名前</th>
							<th><%= link_to @picture.user.name, user_path(@picture.user), class: "word-break" %></th>
						</tr>
					<% else %>
						<tr>
							<th class="nowrap">ニックネーム</th>
							<th>
								<p><%= link_to @picture.user.nickname, user_path(@picture.user), class: "word-break" %></p>
							</th>
						</tr>
					<% end %>
						<tr>
							<th class="nowrap">ステータス</th>
							<th><p><%= @picture.user.status %></p></th>
						</tr>
				</tbody>
			</table>
			<!-- 投稿ユーザプロフィール -->

			<% if @picture.user == current_user %>
				<%= link_to "作品を投稿する", new_picture_path, class: "btn btn-primary", style: "margin-bottom: 10px; padding: 8px 90px;" %>
			<% end %>

			<!-- 投稿ユーザの投稿作品 -->
			<h5><b>投稿作品</b></h5>

			<table class="table">
				<tbody>
					<tr>	
						<% @pictures.each do |picture| %>
							<td>
								<%= link_to picture_path(picture)do %>
									<%= attachment_image_tag picture.picture_images[0], :image, size: "80x80", format: 'jpeg', fallback: "no_image_square.jpg", style: "margin: 0;" %>
									<div class="post-nowrap">
										<span class="index-title"><%= picture.title %></span>
									</div>
								<% end %>
							</td>
						<% end %>
					</tr>
				</tbody>
			</table>

			<% if @picture.user.pictures.count > 3 %>
				<%= link_to 'もっと見る', controller: "pictures", action: "index", user_id: @picture.user_id %>
			<% end %>
			<!-- 投稿ユーザの投稿作品 -->
		</div>
	</div>
</div>