config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  get 'inquiries/new'
  post 'inquiries/confirm'
  post 'inquiries/thanks'

  devise_for :users
  patch 'users/withdraw' => 'users#withdraw', as: 'withdraw'
  resources :users, only: [:show, :index, :edit, :update] do
    resources :payments, only: [:create, :index]
  end

  get 'comics' => "pictures#comics", as: :comics
  get 'illustrations' => "pictures#illustrations", as: :illustrations
  get 'bookmarks' => "pictures#bookmarks", as: :bookmarks
  resources :pictures do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
    resource :bookmarks, only: [:create, :destroy]
  end
  
  resources :genres, only: [:index, :create,:edit, :update]
  resources :messages, only: [:create]
  resources :rooms, only: [:create, :show, :index]
  get 'search', to: "searches#search"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :picture
  
  validates :user_id, :uniqueness => { :scope => :picture_id }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :picture
  
  validates :comment, presence: true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :room_id, uniqueness: { scope: :user_id }
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :picture
  validates :user_id, :uniqueness => { :scope => :picture_id }
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :pictures, dependent: :destroy

  validates :genre, presence: true
  validates :genre, length: {maximum: 15}
  validates :is_active, inclusion: { in: [true, false] }

  # ジャンル検索で、作品を探すロジック
  def self.search_genre(word)
    where(is_active: true).where("genre LIKE?","%#{word}%")
    					  .pluck("id")
  end
end

app/models/inquiry.rb
class Inquiry
  include ActiveModel::Model

  attr_accessor :name, :email, :message

  validates :name, :email, :message, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :message, presence: true
end

app/models/payment.rb
class Payment < ApplicationRecord
	belongs_to :user

	enum status: { 未払い: 0, 支払い済み: 1 }

	def self.this_month_payment
		5000
	end

	def self.tax
		1.1
	end

	def self.taxin_payment
		self.this_month_payment * self.tax
	end
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :user
  belongs_to :genre
  has_many :picture_images, dependent: :destroy
  accepts_nested_attributes_for :picture_images
  accepts_attachments_for :picture_images, attachment: :image
  has_many :bookmarks, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy

  enum status: { イラスト: 0, マンガ: 1 }

  scope :genre_active,  -> { joins(:genre).where(genres: {is_active: true}) }
  scope :user_active,  -> { joins(:user).where(users: {is_deleted: false}) }

  # ログインユーザがすでにいいねしているか確かめるロジック
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  # ログインユーザがすでにお気に入り登録しているか確かめるロジック
  def bookmark_by?(user)
    bookmarks.where(user_id: user.id).exists?
  end
   
  # ユーザ詳細画面にて投稿された作品を表示するロジック
  def self.user_picture_limit4(status)
    where(status: status).joins(:genre)
                         .where(genres: {is_active: true})
                         .order(id: "DESC")
                         .limit(4)
  end

  # ユーザ詳細画面にて作品を表示するロジック
  def self.genre_user_active
    joins(:genre, :user).where(genres: {is_active: true}, users: {is_deleted: false})                    
  end

  # 検索窓でイラストまたはマンガを探すロジック
  def self.search_picture(status, word)
    where(status: status).where("title LIKE?","%#{word}%")
                         .joins(:genre, :user)
                         .where(genres: {is_active: true}, users: {is_deleted: false})
  end

  # 検索窓でジャンル関連の作品を探すロジック
  def self.search_genre_picture(genres)
    where(genre_id: genres).joins(:user).where(users: {is_deleted: false})
  end

  # ジャンルとユーザが有効で、マンガまたはイラストを取得するロジック
  def self.picture_user_genre_active(status)
    where(status: status).joins(:genre, :user)
                         .where(genres: {is_active: true} ,users: {is_deleted: false})
  end

  # ジャンルが有効で、マンガまたはイラストを取得するロジック
  def self.picture_genre_active(status)
    where(status: status).joins(:genre)
                         .where(genres: {is_active: true})
  end

  # ユーザが有効で、マンガまたはイラストを取得するロジック
  def self.picture_user_active(status)
    where(status: status).joins(:user)
                         .where(users: {is_deleted: false})
  end

  validates :title, :introduction, :status, presence: true
end

app/models/picture_image.rb
class PictureImage < ApplicationRecord
  belongs_to :picture, optional: true
  attachment :image
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :users, through: :entries
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :payments, dependent: :destroy
  has_many :pictures, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :rooms, through: :entries
  attachment :profile_image

  enum status: { 無料会員: 0, 有料会員: 1, 講師: 2 }

  # 有効会員のみログインできる機能
  def active_for_authentication?
    super && (self.is_deleted == false)
  end

  # ユーザ検索機能
  def self.search_user(word)
    where(is_deleted: false).where("name LIKE?","%#{word}%")
                            .or(where(is_deleted: false)
                            .where("nickname LIKE?","%#{word}%"))
  end

  # @userとログインユーザがEntryモデルに相互登録されていることを確かめるロジック
  def login_user_check_entry(other_user)
    result = {
      isRoom: false,
      roomId: nil,
      room: nil,
      entry: nil
    }

    currentUserEntry = entries
    userEntry = other_user.entries
    isRoom = false
    currentUserEntry.each do |cu|
      userEntry.each do |u|
        if cu.room_id == u.room_id
          isRoom = true
          result[:isRoom] = isRoom
          result[:roomId] = cu.room_id
        end
      end
    end
    unless isRoom
      result[:room] = Room.new
      result[:entry] = Entry.new
    end
    result
  end

  validates :name, :name_kana, :email, :status, presence: true
  validates :nickname, length: {maximum: 25}
end

app/controllers/inquiries_controller.rb
class InquiriesController < ApplicationController
  def new
  	@inquiry = Inquiry.new
  end

  def confirm
    @inquiry = Inquiry.new(inquiry_params)
    if @inquiry.valid?
      render :confirm
    else
      render :new
    end
  end

  def thanks
    @inquiry = Inquiry.new(inquiry_params)    
    InquiryMailer.received_email(@inquiry).deliver

    render :thanks
  end

  private
  def inquiry_params
    params.require(:inquiry).permit(:name, :email, :message)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/inquiries/confirm.html.erb
<div class="container">
  <div class="row">
    <%= form_for @inquiry, :url => inquiries_thanks_path do |f| %>
      <div class="col-sm-6 col-sm-offset-3 col-md-4 col-md-offset-4 form-background">
        <h1 class="text-center inquiry-title">お問い合わせ</h1>

        <div class="col-md-10 form-space">
          <label>名前</label><br>
          <div class="confirm word-break">
            <%= f.hidden_field :name %>
            <%= @inquiry.name %>
          </div>
        </div>

        <div class="col-md-10 form-space">
          <label>メールアドレス</label><br>
          <div class="confirm word-break">
            <%= f.hidden_field :email %>
            <%= @inquiry.email %>
          </div>
        </div>

        <div class="col-md-12 form-space">
          <label>お問い合わせ内容</label><br>
          <div class="confirm word-break">
            <%= f.hidden_field :message %>
            <%= simple_format(@inquiry.message) %>
          </div>
        </div>

        <div class="col-md-12 form-space">
          <%= f.submit '送信', class: 'btn btn-primary btn-block' %>
        </div>
      </div>
    <% end %>
  </div>
</div>  

app/views/inquiries/new.html.erb
<div class="container">
  <div class="row">
    <%= form_for @inquiry, :url => inquiries_confirm_path do |f| %>
      <div class="col-sm-6 col-sm-offset-3 col-md-4 col-md-offset-4 form-background">
        <h1 class="text-center inquiry-title">お問い合わせ</h1>

        <div class="col-md-10 form-space">
          <label>名前<span class="text-danger">（必須）</span></label><br>
          <%= f.text_field :name, placeholder: "山田太郎", class: "form-control", :required => true  %>
        </div>

        <div class="col-md-10 form-space">
          <label>メールアドレス<span class="text-danger">（必須）</span></label><br>
          <%= f.text_field :email, placeholder: "example@email.com", class: "form-control", :required => true %>
        </div>

        <div class="col-md-12 form-space">
          <label>お問い合わせ内容</label><br>
          <%= f.text_area :message, class: "form-control", size: "0x6", :required => true %>
        </div>

        <div class="col-md-12 form-space">
          <%= f.submit '確認', class: 'btn btn-primary btn-block' %>
        </div>
      </div>
    <% end %>
  </div>
</div>  

app/views/inquiries/thanks.html.erb
<div class="container">
  <div class="row">
		<h1 class="text-center thanks-title">お問い合わせ</h1>
		<p class="text-center thanks-text">
			お問い合わせいただきありがとうございました。<br>
			内容を確認次第、お客様のメールアドレスに返信いたします。<br>
			万が一返信がない場合は、お手数ですがexample@email.comにご連絡ください。
		</p>
		<div class="thanks-image">
			<%= image_tag('business_ojigi_woman.png', style: "width: 200px; height: 300px;") %>
		</div>
	</div>
</div>	